# Generated by Django 2.2 on 2019-05-23 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrylist',
            name='awards',
            field=models.CharField(blank=True, default='未设置', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='entrylist',
            name='score_kind',
            field=models.CharField(blank=True, default='未设置', max_length=100, null=True),
        ),
    ]
