# Generated by Django 2.2 on 2019-05-06 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='account_status',
            field=models.CharField(default='未创建', max_length=20),
        ),
    ]
