# Generated by Django 2.2 on 2019-05-21 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrylist',
            name='score',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
