# Generated by Django 2.2 on 2019-05-24 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20190523_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='account_status',
        ),
        migrations.AddField(
            model_name='activity',
            name='entry_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='entry_count',
            field=models.IntegerField(default=0),
        ),
    ]
